# Dockerfile.frontend
FROM node:18 AS builder

WORKDIR /app

COPY frontend/fut-game/package*.json ./
RUN npm install

COPY frontend/fut-game .

EXPOSE 8080

# --host 0.0.0.0 e --port 8080
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "8080"]
